### ISSUE TITLE
Method too large exception with jdk19

### ISSUE THREAD

**Issue by vitali-pr** [nguyenq/lept4j#20]
Windows 10, OpenJDK jdk 19, lept4j 1.16.2.
It's ok with OpenJDK jdk 18.

'Method too large' Exception thrown while trying to load Leptonica instance. The problem looks close to what is described at https://github.com/nguyenq/lept4j/blob/master/src/main/resources/readme.txt

Caused by: jdk.internal.org.objectweb.asm.MethodTooLargeException: Method too large: jdk/proxy2/$Proxy2.<clinit> ()V
	at java.base/jdk.internal.org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2120)
	at java.base/jdk.internal.org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:543)
	at java.base/java.lang.reflect.ProxyGenerator.generateClassFile(ProxyGenerator.java:507)
	at java.base/java.lang.reflect.ProxyGenerator.generateProxyClass(ProxyGenerator.java:179)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.defineProxyClass(Proxy.java:558)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.build(Proxy.java:670)
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:429)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:427)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037)
	at com.sun.jna.Native.loadLibrary(Native.java:674)
	at com.sun.jna.Native.loadLibrary(Native.java:656)
	at net.sourceforge.lept4j.util.LoadLibs.getLeptonicaInstance(LoadLibs.java:81)
	at net.sourceforge.lept4j.Leptonica.<clinit>(Leptonica.java:36)
	... 8 more

**Comment by nguyenq** [comment]
Right, JDK 19 further limits the size of the methods. We have updated `readme.txt` to document the new exception and limitation. The path forward for you might be to use `Leptonica1` class instead if `Leptonica` class throws the exception in your code.

**Comment by vitali-pr** [comment]
@nguyenq, thank you very much!
Leptonica1 indeed helps on Windows. But lept4j is not self contained on Linux. It depends on lept5 native lib installed on the system. Leptonica1 class of lept4j expects lept5 lib of version 1.82 and otherwise can't be loaded. (For other viewers: It has a list of exports it uses and it is not loaded if some of the export is not found in lept5 lib). Having lept5 1.82.0 is quite a strict requirement and not easy to achieve on older Linux versions.

**Comment by nguyenq** [comment]
@vitali-pr You can override the version of a dependency by explicitly specifying it in the POM.

**Comment by vitali-pr** [comment]
Our fix was to use Leptonica1 for java 19 and above and Leptonica for earlier versions. This way the latest liblept is required on Linux only if java 19+ is used.

**Comment by nguyenq** [comment]
Thanks for sharing.
