### ISSUE TITLE
Exception UnsatisfiedLinkError: Error looking up function 'l_bootnum_gen1'

### ISSUE THREAD

**Issue by djx2unv** [nguyenq/lept4j#5]
Having problems with this exception. I've installed the 86_64 lib from rpm resources. The instalation added two libs in /usr/lib64, liblept.so.4 and liblept.so.4.0.3.

And I've checked the documentation and the Class Leptonica, the Pointer is there. 
Thanks for your attention.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'l_bootnum_gen1': /usr/lib64/liblept.so.4.0.3: undefined symbol: l_bootnum_gen1
    at com.sun.jna.Function.<init>(Function.java:208)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:536)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:513)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:499)
    at com.sun.jna.Native.register(Native.java:1509)
    at com.sun.jna.Native.register(Native.java:1396)
    at com.sun.jna.Native.register(Native.java:1156)
    at net.sourceforge.lept4j.Leptonica1.<clinit>(Leptonica1.java:42)
    at net.sourceforge.lept4j.util.LeptUtilsTest.testRemoveLines(LeptUtilsTest.java:127)
    at com.lept4jmaster.main.Executer.main(Executer.java:13)
```

**Comment by nguyenq** [comment]
We could not reproduce the issue. The specified method invoked successfully in Leptonica 1.73, which is present as `liblept.so.5` on Ubuntu.

**Comment by djx2unv** [comment]
Okay, thanks anyway for your reply!
